name: Publish Dev

on:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: test_github_tags

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get tags
        run: |
          echo "Getting tags of branch and master"

          git fetch --prune --unshallow

          BRANCH_TAG=$(git describe)
          BRANCH_TAG=${BRANCH_TAG#v*}
          BRANCH_TAG=${BRANCH_TAG%%-*}
          echo "::set-env name=BRANCH_TAG::${BRANCH_TAG}"

          MASTER_TAG=$(git describe origin/master)
          MASTER_TAG=${MASTER_TAG#v*}
          MASTER_TAG=${MASTER_TAG%%-*}
          echo "::set-env name=MASTER_TAG::${MASTER_TAG}"

      - name: Check tag is higher than master
        run: |
          echo "Checking tag is higher in branch"

          echo "master is ${{ env.MASTER_TAG }}"
          echo "branch is ${{ env.BRANCH_TAG }}"
          [ "${{ env.BRANCH_TAG }}" != "$(echo -e "${{ env.BRANCH_TAG }}\n${{ env.MASTER_TAG }}" | sort -V | head -n1)" ] || echo "branch tag is not higher than master's" && exit 1

      - name: Build Image
        run: |
          echo "Building docker image"

      - name: Tag Image
        run: |
          echo "Tagging docker image"

      - name: Push to registry
        run: |
          echo "Pushing image to registry"
