name: Publish Dev

on:
  workflow_dispatch:

env:
  IMAGE_NAME: kennylouie/gha

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get tag
        run: |
          echo "Getting tag of master"

          git fetch --prune --unshallow

          MASTER_TAG=$(git describe origin/master)
          MASTER_TAG=${MASTER_TAG#v*}
          MASTER_TAG=${MASTER_TAG%%-*}

      - name: Publish docker image
        run: |
          echo "Build, tag, and publish docker image"
          echo $IMAGE_NAME:latest $IMAGE_NAME:${{ env.MASTER_TAG }}
