name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: test_github_tags

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: kennylouie/dkr_pub@v0.0.1
        with:
          name: $IMAGE_NAME
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
