name: Publish Dev

on:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: test_github_tags

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get tag
        run: |
          echo "Getting tag"
          git fetch --prune --unshallow

          BRANCH_TAG=$(git describe)
          echo "::set-env name=BRANCH_TAG::${BRANCH_TAG#v*}"
          echo ${{ env.BRANCH_TAG }}

          git checkout origin/master
          MASTER_TAG=$(git describe)
          echo "::set-env name=MASTER_TAG::${MASTER_TAG#v*}"
          echo ${{ env.MASTER_TAG }}

      - name: Check tag is higher than master
        run: |
          echo "Incrementing tag patch"
          echo ${{ env.MASTER_TAG }}
          echo ${{ env.BRANCH_TAG }}

      - name: Build Image
        run: |
          echo "Building docker image"

      - name: Build Image
        run: |
          echo "Building docker image"

      - name: Push to registry
        run: |
          echo "Pushing image to registry"
