name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: test_github_tags

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get tag number
        run: |
          echo ${GITHUB_REF##*/}
          echo $IMAGE_NAME
          echo "::set-env IMAGE_NAME=action_state::changed"
          echo $IMAGE_NAME
          [ 1 == 2 ] && echo "no"
          [ 1 == 1 ] && echo "yes"
            
  push:
    needs: tag
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: check tag is higher
        run: |
          echo "next step"
