name: Publish Dev

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: test_github_tags

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Ruby tests

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
      - run: |
        echo "Getting tag"
        echo $GITHUB_REF
        echo "::set-env name=TAG::${GITHUB_REF##*/}"
        [ -z "${{ env.TAG }}" ] && exit 1
        echo "${{ env.TAG }}"

    steps:
      - name: Increment tag patch
      - run: |
        echo "Incrementing tag patch"

    steps:
      - name: Build Image
      - run: |
        echo "Building docker image"

    steps:
      - name: Build Image
      - run: |
        echo "Building docker image"

    steps:
      - name: Push to registry
      - run: |
        echo "Pushing image to registry"
