name: Publish Prod

on:
  release:

env:
  IMAGE_NAME: kennylouie/gha

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get tag from release
        run: |
          echo "Getting tag of master"
          echo $GITHUB_REF
          printenv
