name: Publish Prod

on:
  release:

env:
  IMAGE_NAME: kennylouie/gha

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get tag from release
        run: |
          echo "Getting tag from release"
          echo github ref is $GITHUB_REF
          TAG=${GITHUB_REF##v*}
          TAG=${TAG##*/}
          echo tag is $TAG
          echo "::set-env name=TAG::${TAG}"
