name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: test_github_tags

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get tag of current branch
        run: |
          echo $GITHUB_REF
          echo ::set-env name=TAG::${GITHUB_REF#refs/*/}
          [ -z ${{ env.TAG}} ] && echo "no tag set" && exit 1
          echo $IMAGE_NAME:${{ env.TAG }}
          
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          
      - name: Get tag of last release
        run: |
          docker images
