name: Build Prod

on:
  release:
    types: [published]

env:
  IMAGE_NAME: kennylouie/gha

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        run: |
          echo "Getting tag from release"
          echo github ref is $GITHUB_REF
          TAG=${GITHUB_REF##v*}
          TAG=${TAG##*/}
          echo tag is $TAG
          echo "::set-env name=TAG::${TAG}"

      - name: Get tag
        run: |
          echo ${{ env.TAG }}
