name: cicd-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: generate change
        run: |
          git fetch --prune --unshallow
          git status
          echo ${{ github.ref }}
          export LATEST_TAG=$(git --no-pager tag | sort -V | tail -n1)
          export PREV_TAG=$(git --no-pager tag | sort -V | tail -n2 | head -n1)
          git log ${PREV_TAG}...${LATEST_TAG} --no-pager --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit > CHANGE.md
          ls
          pwd

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGE.md
          draft: false
          prerelease: false
